# PostgreSQL database

default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.credentials.fetch("DB_HOST", "localhost") %>
  port: <%= Rails.application.credentials.fetch("DB_PORT", "5432") %>
  username: <%= Rails.application.credentials.fetch("DB_USERNAME", "postgres") %>
  password: <%= Rails.application.credentials.fetch("DB_PASSWORD", "") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: message_me_development

test:
  <<: *default
  database: message_me_test

production:
  <<: *default
  database: <%= Rails.application.credentials.fetch("DB_NAME", "message_me_production") %>
